### PR TITLE
DBZ-3837 upgrade Debezium UI to Debezium 1.6.1.Final

### PR DESCRIPTION
**Pull request by rk3rn3r**
closes https://issues.redhat.com/browse/DBZ-3837

### CODE REVIEW

**Review by gunnarmorling — APPROVED** [review]
LGTM, but @mdrillin is reporting issues from local testing. Feel free to merge yourself once those are sorted out.

**Comment by gunnarmorling** [comment]
Also see the test failures.

**Comment by uidoyen** [comment]
I tested locally the build is successful but cypress is failing might be because of we still have `1.5`. We need to update accordingly.

**Comment by rk3rn3r** [comment]
@uidoyen I updated the e2e tests, I guess and CI for it is green.
@gunnarmorling the issue seems to be performance related. I had to increase `-Ddebezium.test.records.waittime` from the default, which is 2, to `14` to pass tests locally. Testing on CI now.

**Comment by rk3rn3r** [comment]
@gunnarmorling a waittime of 20 solved it for CI. Did we introduce some perfomance issue from 1.5 to 1.6 causing it maybe?

**Comment by gunnarmorling** [comment]
> Did we introduce some perfomance issue from 1.5 to 1.6 causing it maybe?

Well, I hope not. Can you log a DBZ issue please with all the required
context? Thx!

>

**Comment by rk3rn3r** [comment]
Done https://issues.redhat.com/browse/DBZ-3872

**Pull request merged**
