### PR TITLE
DBZ-6363 Replacing MongoDbContainer with MongoDbReplicaSet and fixing mongodb visibility for other containers

### PR DESCRIPTION
**Pull request by jcechace**
The few tests I tried worked on my MacOS machine. Somebody should try it on linux.

This PR supersedes ##700

### CODE REVIEW

**Comment by jcechace** [comment]
Superseded by #701

**Comment by jcechace** [comment]
@rk3rn3r  @ani-sha  I moved this under new Jira ticket and polished a code a bit (mainly moving things which should be moved directly to debezium-testcontainers). This seem to work on MacOS. 

Somebody should take it from here and make sure it also works with linux :).

**Comment by Naros** [comment]
Hi @jcechace, I ran the test suite locally, and it works like a charm.  I'm going to do the following:

1. Apply the change in the main repository against Debezium 2.3.0-SNAPSHOT.
2. Add a commit to this PR to remove the `@Disabled` annotation on the MongoDB tests.
3. Move the Debezium UI repository to Debezium 2.3.0-SNAPSHOT.
4. Rebase this PR and merge

This should get everything lined up and working again.  Thanks for all the help on this!

**Comment by Naros** [comment]
Applied to main (=2.3).

**Comment by rk3rn3r** [comment]
Thx a lot @jcechace! :pray:
Great work

**Pull request merged**
