### PR TITLE
Dbz 4146

### PR DESCRIPTION
**Pull request by indraraj**
https://issues.redhat.com/browse/DBZ-4146

Using backend response to fetch the SMT list and their properties.

### CODE REVIEW

**Comment by indraraj** [comment]
Backend End point fixed, it's good to go.

**Comment by mdrillin** [comment]
@indraraj  - I'm seeing a couple issues while testing this.  Are you seeing the same?

1) Add a transformation.  The first time I select a transformation type, I get the following console warning:

react-dom.development.js?a814:67 Warning: Received the string `true` for the boolean attribute `checked`. Although this works, it will not work as expected if you pass the string "false". Did you mean checked={true}?
    at input
    at div
    at Checkbox (webpack-internal:///../../node_modules/@patternfly/react-core/dist/esm/components/Checkbox/Checkbox.js:19:9)
    at div
    at SplitItem (webpack-internal:///../../node_modules/@patternfly/react-core/dist/esm/layouts/Split/SplitItem.js:16:11)
    at div
    at Split (webpack-internal:///../../node_modules/@patternfly/react-core/dist/esm/layouts/Split/Split.js:16:11)
    at FormCheckboxComponent (webpack-internal:///./src/app/components/formHelpers/FormCheckboxComponent.tsx:22:108)
...

2) After adding a transformation, click apply.  Then click next to next page.  Then click 'back' to go back to SMT page.  Get the following error:

TransformsStep.tsx?f72a:55 Uncaught TypeError: response.forEach is not a function
    at getOptions (TransformsStep.tsx?f72a:55)
    at eval (TransformsStep.tsx?f72a:319)
    at Array.map (<anonymous>)
    at Object.eval [as children] (TransformsStep.tsx?f72a:304)
    at WithLoader.render (WithLoader.tsx?e511:98)
    at finishClassComponent (react-dom.development.js?a814:17485)
    at updateClassComponent (react-dom.development.js?a814:17435)
    at beginWork (react-dom.development.js?a814:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js?a814:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?a814:3994)
getOptions @ TransformsStep.tsx?f72a:55
eval @ TransformsStep.tsx?f72a:319
eval @ TransformsStep.tsx?f72a:304
WithLoader.render @ WithLoader.tsx?e511:98
...

**Comment by indraraj** [comment]
Hey @mdrillin for the first points looks like its backend response issue for the type boolean default value is coming as "true"
```
defaultValue: "true"
title: "Add source topic name into key"
type: "BOOLEAN"
x-name: "key.enforce.uniqueness"
```

**Review by mdrillin — APPROVED** [review]
Looks good - thanks!

**Pull request merged**
