### PR TITLE
DBZ-5043 Change namespace of schema history and remove database.server.name

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-5043

Changes related to https://github.com/debezium/debezium/pull/3804

### CODE REVIEW

**Comment by jpechane** [comment]
@vjuranek Could you please rebase the PR?

**Comment by jpechane** [comment]
@vjuranek Please there are compilation failures in tests referring to renamed classes

**Comment by vjuranek** [comment]
yes, I noticed @jpechane . I still have some issues to run UI test locally, so to speed it up, I'm using GH actions instead. Until this is a draft, feel free to ignore any changes.

**Comment by jpechane** [comment]
@vjuranek End-to-End tests are still failing, does this PR depends on something else?

**Comment by jpechane** [comment]
@vjuranek I've rebuilt the `nightly` image but the failure is still present.

**Pull request merged**
