### PR TITLE
Using github api to obtain git revision

### PR DESCRIPTION
**Pull request by uidoyen**
Fixes https://github.com/debezium/debezium-ui/pull/332

### CODE REVIEW

**Comment by indraraj** [comment]
Hey, @uidoyen can you list the testing steps.

**Comment by uidoyen** [comment]
> Hey, @uidoyen can you list the testing steps.

@indraraj test steps are simple as below
Run ui on `dev` or `prod` mod. Click help icon on header top right corner you should be able to see build hash as below screenshot
Screenshot from 2021-07-08 21-48-56

**Comment by indraraj** [comment]
> > Hey, @uidoyen can you list the testing steps.
> 
> @indraraj I am not sure what testing steps you are referring to but you can follow below steps:
> 
> Run ui on `dev` or `prod` mod. Click help icon on header top right corner you should be able to see build hash as below screenshot
> Screenshot from 2021-07-08 21-48-56

I was talking about the UI build fail issue, but now that i realise this is not using git cmd at all it may not be needed

**Review by indraraj — APPROVED** [review]
Looks good.

**Comment by indraraj** [comment]
Hey @uidoyen I was thinking if we should not work directly from the main repo but from our fork, leave the main repo clean with some occasion required feature branches.

**Pull request closed without merging**
