### PR TITLE
Webpack update; RTL Implementation; Lerna dependency update

### PR DESCRIPTION
**Pull request by indraraj**
- Updated the webpack build config files. making the dev and prod mode much closer.
- Added the yarn cmd `yarn start:prod` to run the `prod` mode UI build over node webserver. 
- Updated the Lerna dependency.
- Implemented the React Testing Library in place of Enzyme .

PS: Apologies for trying to fix multiple things in open pr and getting it bigger, but I didn't have much choice as almost all the issues were intertwined.

### CODE REVIEW

**Comment by indraraj** [comment]
https://github.com/debezium/debezium-ui/pull/362 covered in this PR, closing it.

**Comment by uidoyen** [comment]
@indraraj Cypress test seems to be failed. Is it ready for review?

**Comment by indraraj** [comment]
It's good to review. This pr didn't involve any code hack or trick to get past. as you would see it locally. (I have personally tested via fresh checkout). Though there seems to be an issue with Github action which I assume need some separate fixing.

**Comment by uidoyen** [comment]
> It's good to review. This pr didn't involve any code hack or trick to get past. as you would see it locally. (I have personally tested via fresh checkout). Though there seems to be an issue with Github action which I assume need some separate fixing.

Lets keep this on hold until we fix GH action issue. WDYT?

**Comment by indraraj** [comment]
> > It's good to review. This pr didn't involve any code hack or trick to get past. as you would see it locally. (I have personally tested via fresh checkout). Though there seems to be an issue with Github action which I assume need some separate fixing.
> 
> Lets keep this on hold until we fix GH action issue. WDYT?

sure

**Review by mdrillin — APPROVED** [review]
looks good to me - nice work!

**Review by uidoyen — APPROVED** [review]
Nice work! LGTM

**Pull request merged**
