### PR TITLE
DBZ-3779: Import Pattern-fly CSS from @patternfly/patternfly

### PR DESCRIPTION
**Pull request by indraraj**
- Importing patternfly css only from `@patternfly/patternfly`.
- using `MiniCssExtractPlugin.loader`.

### CODE REVIEW

**Comment by uidoyen** [comment]
@indraraj I got the following WARNING upon running `yarn start` after `yarn install` and `yarn build`
```
WARNING in chunk src_app_shared_index_ts-src_i18n_index_ts-webpack_sharing_consume_default_react-dom_react-dom-2016c9 [mini-css-extract-plugin]
Conflicting order. Following module has been added:
 * css ../../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!../../node_modules/postcss-loader/src/index.js??ruleSet[1].rules[1].use[2]!./src/app/components/ApplicationErrorPage.css
despite it was not able to fulfill desired ordering with these modules:
 * css ../../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!../../node_modules/postcss-loader/src/index.js??ruleSet[1].rules[1].use[2]!./src/app/layout/layout.css
   - couldn't fulfill desired order of chunk group(s) 
```

Probably you could add `ignoreOrder: true` under `MiniCssExtractPlugin({ignoreOrder: true, ...` to resolve.

**Comment by indraraj** [comment]
Thanks for catching, update the PR with a fix.

**Review by mdrillin — APPROVED** [review]
lgtm - will hold off on merge for Ashique to retest

**Comment by uidoyen** [comment]
LGTM. Thanks.

**Pull request merged**
