### PR TITLE
DBZ-5313:Edit a connector in Debezium UI

### PR DESCRIPTION
**Pull request by uidoyen**

### CODE REVIEW

**Comment by indraraj** [comment]
While randomly clicking on the side nav I got this error, screenshot below 
image
maybe this will help

**Review by indraraj — CHANGES_REQUESTED** [review]
added two comments

**Comment by indraraj** [comment]
also WDYT about demoing it in our UI call?

**Comment by uidoyen** [comment]
> While randomly clicking on the side nav I got this error, screenshot below image maybe this will help

It should be fine now.

**Comment by indraraj** [comment]
@uidoyen  If you want you can get this in since its an extensive PR, and for any further improvement we can follow up in subsequent PR's

**Pull request merged**
