### PR TITLE
DBZ-4460 Update UI backend to fetch generated schema from connector archives

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-4460
- [x] Update Debezium UI to obtain the API specs from the connector archives

### CODE REVIEW

**Comment by rk3rn3r** [comment]
@ani-sha can you check out and figure what is causing that NPE in the CI tests?

**Comment by gunnarmorling** [comment]
One comment inline. Any reference to that NPE / or other build failures we supposedly have due to this?

**Comment by gunnarmorling** [comment]
Btw. where are we with the UI frontend changes which I suppose are needed in order to accommodate for this change here? Ideally, they would be part of this very same PR, so we can merge this all at once. Or is the format exactly the same as before, and no UI frontend changes are actually needed? What also seems to be missing from this PR is the removal of the old way for exposing the connector schemas via Quarkus.

**Comment by mdrillin** [comment]
@gunnarmorling iirc, the backend changes can be completed/merged without affecting the current frontend.  Whenever the backend work is ready and merged, I can work on adapting the frontend.  @rk3rn3r can correct me if I am mistaken :-)

**Comment by ani-sha** [comment]
> One comment inline. 

@gunnarmorling I don't see the inline comment.

> Any reference to that NPE / or other build failures we supposedly have due to this?

No, the build failures existed already unrelated to the current changes, even the NPE. 

> Where are we with the UI frontend changes which I suppose are needed in order to accommodate for this change here?

As per discussion in the UI call, the frontend changes would be incorporated by Indra or Ashique after this PR gets merged. After the UI part has been done, we would be finally removing the older way of exposing the schemas.

**Comment by gunnarmorling** [comment]
> As per discussion in the UI call, the frontend changes would be incorporated by Indra or Ashique after this PR gets merged. After the UI part has been done, we would be finally removing the older way of exposing the schemas.

Ok, perfect. That sounds very reasonable 👍 !

**Comment by gunnarmorling** [comment]
> I don't see the inline comment.

Doh, sorry, I forgot to push my review. It was about the Debezium version property being duplicated. I'll push a commit for that myself in a minute.

**Comment by gunnarmorling** [comment]
Follow-up PR is here: https://github.com/debezium/debezium-ui/pull/437

@uidoyen, @indraraj, what's the Jira issue for doing the UI changes for moving to the new endpoint?

**Comment by indraraj** [comment]
https://issues.redhat.com/browse/DBZ-4626 for UI work  @gunnarmorling

**Comment by rk3rn3r** [comment]
https://issues.redhat.com/browse/DBZ-4619 is the correct task @indraraj @gunnarmorling

**Pull request merged**
