### PR TITLE
Abhi.add basic auth kafka connect api

### PR DESCRIPTION
**Pull request by abhishekkh**

### CODE REVIEW

**Comment by abhishekkh** [comment]
## QA plan
```
Terraform will perform the following actions:

  # module.jetstream_debezium_ui.kubernetes_deployment.jetstream_debezium_ui will be created
  + resource "kubernetes_deployment" "jetstream_debezium_ui" {
      + id               = (known after apply)
      + wait_for_rollout = true

      + metadata {
          + generation       = (known after apply)
          + labels           = {
              + "application"                = "jetstream-debezium-ui"
              + "cluster"                    = "bikeshed-red"
              + "component"                  = "jetstream-debezium-ui"
              + "environment"                = "qa"
              + "region"                     = "us-east-1"
              + "tags.datadoghq.com/env"     = "qa"
              + "tags.datadoghq.com/service" = "jetstream-debezium-ui"
              + "tags.datadoghq.com/version" = "1.9.1"
              + "team"                       = "data-platform"
            }
          + name             = "jetstream-debezium-ui"
          + namespace        = "qa"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }

      + spec {
          + min_ready_seconds         = 0
          + paused                    = false
          + progress_deadline_seconds = 600
          + replicas                  = 1
          + revision_history_limit    = 10

          + selector {
              + match_labels = {
                  + "application" = "jetstream-debezium-ui"
                  + "cluster"     = "bikeshed-red"
                  + "component"   = "jetstream-debezium-ui"
                  + "environment" = "qa"
                  + "region"      = "us-east-1"
                  + "team"        = "data-platform"
                }
            }

          + strategy {
              + type = (known after apply)

              + rolling_update {
                  + max_surge       = (known after apply)
                  + max_unavailable = (known after apply)
                }
            }

          + template {
              + metadata {
                  + generation       = (known after apply)
                  + labels           = {
                      + "application"                = "jetstream-debezium-ui"
                      + "cluster"                    = "bikeshed-red"
                      + "component"                  = "jetstream-debezium-ui"
                      + "environment"                = "qa"
                      + "region"                     = "us-east-1"
                      + "tags.datadoghq.com/env"     = "qa"
                      + "tags.datadoghq.com/service" = "jetstream-debezium-ui"
                      + "tags.datadoghq.com/version" = "1.9.1"
                      + "team"                       = "data-platform"
                    }
                  + name             = (known after apply)
                  + resource_version = (known after apply)
                  + self_link        = (known after apply)
                  + uid              = (known after apply)
                }

              + spec {
                  + dns_policy                       = "ClusterFirst"
                  + enable_service_links             = true
                  + host_ipc                         = false
                  + host_network                     = false
                  + host_pid                         = false
                  + hostname                         = (known after apply)
                  + node_name                        = (known after apply)
                  + restart_policy                   = "Always"
                  + service_account_name             = (known after apply)
                  + share_process_namespace          = false
                  + termination_grace_period_seconds = 30

                  + container {
                      + image                      = "611689975770.dkr.ecr.us-east-1.amazonaws.com/jetstream-debezium-ui:latest"
                      + image_pull_policy          = "Always"
                      + name                       = "jetstream-debezium-ui"
                      + stdin                      = false
                      + stdin_once                 = false
                      + termination_message_path   = "/dev/termination-log"
                      + termination_message_policy = (known after apply)
                      + tty                        = false

                      + env {
                          + name = "DD_AGENT_HOST"

                          + value_from {

                              + field_ref {
                                  + api_version = "v1"
                                  + field_path  = "status.hostIP"
                                }
                            }
                        }
                      + env {
                          + name = "DD_ENV"

                          + value_from {

                              + field_ref {
                                  + api_version = "v1"
                                  + field_path  = "metadata.labels['tags.datadoghq.com/env']"
                                }
                            }
                        }
                      + env {
                          + name = "DD_SERVICE"

                          + value_from {

                              + field_ref {
                                  + api_version = "v1"
                                  + field_path  = "metadata.labels['tags.datadoghq.com/service']"
                                }
                            }
                        }
                      + env {
                          + name = "DD_VERSION"

                          + value_from {

                              + field_ref {
                                  + api_version = "v1"
                                  + field_path  = "metadata.labels['tags.datadoghq.com/version']"
                                }
                            }
                        }
                      + env {
                          + name  = "KAFKA_CONNECT_URIS"
                          + value = "https://jetstream-debezium.qa.us-east-1.mq01-qa.aws.marqeta.io"
                        }
                      + env {
                          + name  = "AUTH_USER"
                          + value = "admin"
                        }
                      + env {
                          + name  = "AUTH_PASS"
                          + value = "xaU!9$@Xx8Wcp4YA"
                        }

                      + port {
                          + container_port = 8080
                          + name           = "dbzui-port"
                          + protocol       = "TCP"
                        }

                      + resources {
                          + limits {
                              + cpu    = (known after apply)
                              + memory = (known after apply)
                            }

                          + requests {
                              + cpu    = (known after apply)
                              + memory = (known after apply)
                            }
                        }

                      + volume_mount {
                          + mount_path        = (known after apply)
                          + mount_propagation = (known after apply)
                          + name              = (known after apply)
                          + read_only         = (known after apply)
                          + sub_path          = (known after apply)
                        }
                    }

                  + image_pull_secrets {
                      + name = (known after apply)
                    }

                  + volume {
                      + name = (known after apply)

                      + aws_elastic_block_store {
                          + fs_type   = (known after apply)
                          + partition = (known after apply)
                          + read_only = (known after apply)
                          + volume_id = (known after apply)
                        }

                      + azure_disk {
                          + caching_mode  = (known after apply)
                          + data_disk_uri = (known after apply)
                          + disk_name     = (known after apply)
                          + fs_type       = (known after apply)
                          + kind          = (known after apply)
                          + read_only     = (known after apply)
                        }

                      + azure_file {
                          + read_only   = (known after apply)
                          + secret_name = (known after apply)
                          + share_name  = (known after apply)
                        }

                      + ceph_fs {
                          + monitors    = (known after apply)
                          + path        = (known after apply)
                          + read_only   = (known after apply)
                          + secret_file = (known after apply)
                          + user        = (known after apply)

                          + secret_ref {
                              + name      = (known after apply)
                              + namespace = (known after apply)
                            }
                        }

                      + cinder {
                          + fs_type   = (known after apply)
                          + read_only = (known after apply)
                          + volume_id = (known after apply)
                        }

                      + config_map {
                          + default_mode = (known after apply)
                          + name         = (known after apply)
                          + optional     = (known after apply)

                          + items {
                              + key  = (known after apply)
                              + mode = (known after apply)
                              + path = (known after apply)
                            }
                        }

                      + csi {
                          + driver            = (known after apply)
                          + fs_type           = (known after apply)
                          + read_only         = (known after apply)
                          + volume_attributes = (known after apply)
                          + volume_handle     = (known after apply)

                          + controller_expand_secret_ref {
                              + name      = (known after apply)
                              + namespace = (known after apply)
                            }

                          + controller_publish_secret_ref {
                              + name      = (known after apply)
                              + namespace = (known after apply)
                            }

                          + node_publish_secret_ref {
                              + name      = (known after apply)
                              + namespace = (known after apply)
                            }

                          + node_stage_secret_ref {
                              + name      = (known after apply)
                              + namespace = (known after apply)
                            }
                        }

                      + downward_api {
                          + default_mode = (known after apply)

                          + items {
                              + mode = (known after apply)
                              + path = (known after apply)

                              + field_ref {
                                  + api_version = (known after apply)
                                  + field_path  = (known after apply)
                                }

                              + resource_field_ref {
                                  + container_name = (known after apply)
                                  + quantity       = (known after apply)
                                  + resource       = (known after apply)
                                }
                            }
                        }

                      + empty_dir {
                          + medium     = (known after apply)
                          + size_limit = (known after apply)
                        }

                      + fc {
                          + fs_type      = (known after apply)
                          + lun          = (known after apply)
                          + read_only    = (known after apply)
                          + target_ww_ns = (known after apply)
                        }

                      + flex_volume {
                          + driver    = (known after apply)
                          + fs_type   = (known after apply)
                          + options   = (known after apply)
                          + read_only = (known after apply)

                          + secret_ref {
                              + name      = (known after apply)
                              + namespace = (known after apply)
                            }
                        }

                      + flocker {
                          + dataset_name = (known after apply)
                          + dataset_uuid = (known after apply)
                        }

                      + gce_persistent_disk {
                          + fs_type   = (known after apply)
                          + partition = (known after apply)
                          + pd_name   = (known after apply)
                          + read_only = (known after apply)
                        }

                      + git_repo {
                          + directory  = (known after apply)
                          + repository = (known after apply)
                          + revision   = (known after apply)
                        }

                      + glusterfs {
                          + endpoints_name = (known after apply)
                          + path           = (known after apply)
                          + read_only      = (known after apply)
                        }

                      + host_path {
                          + path = (known after apply)
                          + type = (known after apply)
                        }

                      + iscsi {
                          + fs_type         = (known after apply)
                          + iqn             = (known after apply)
                          + iscsi_interface = (known after apply)
                          + lun             = (known after apply)
                          + read_only       = (known after apply)
                          + target_portal   = (known after apply)
                        }

                      + local {
                          + path = (known after apply)
                        }

                      + nfs {
                          + path      = (known after apply)
                          + read_only = (known after apply)
                          + server    = (known after apply)
                        }

                      + persistent_volume_claim {
                          + claim_name = (known after apply)
                          + read_only  = (known after apply)
                        }

                      + photon_persistent_disk {
                          + fs_type = (known after apply)
                          + pd_id   = (known after apply)
                        }

                      + projected {
                          + default_mode = (known after apply)

                          + sources {
                              + config_map {
                                  + name     = (known after apply)
                                  + optional = (known after apply)

                                  + items {
                                      + key  = (known after apply)
                                      + mode = (known after apply)
                                      + path = (known after apply)
                                    }
                                }

                              + downward_api {
                                  + items {
                                      + mode = (known after apply)
                                      + path = (known after apply)

                                      + field_ref {
                                          + api_version = (known after apply)
                                          + field_path  = (known after apply)
                                        }

                                      + resource_field_ref {
                                          + container_name = (known after apply)
                                          + quantity       = (known after apply)
                                          + resource       = (known after apply)
                                        }
                                    }
                                }

                              + secret {
                                  + name     = (known after apply)
                                  + optional = (known after apply)

                                  + items {
                                      + key  = (known after apply)
                                      + mode = (known after apply)
                                      + path = (known after apply)
                                    }
                                }

                              + service_account_token {
                                  + audience           = (known after apply)
                                  + expiration_seconds = (known after apply)
                                  + path               = (known after apply)
                                }
                            }
                        }

                      + quobyte {
                          + group     = (known after apply)
                          + read_only = (known after apply)
                          + registry  = (known after apply)
                          + user      = (known after apply)
                          + volume    = (known after apply)
                        }

                      + rbd {
                          + ceph_monitors = (known after apply)
                          + fs_type       = (known after apply)
                          + keyring       = (known after apply)
                          + rados_user    = (known after apply)
                          + rbd_image     = (known after apply)
                          + rbd_pool      = (known after apply)
                          + read_only     = (known after apply)

                          + secret_ref {
                              + name      = (known after apply)
                              + namespace = (known after apply)
                            }
                        }

                      + secret {
                          + default_mode = (known after apply)
                          + optional     = (known after apply)
                          + secret_name  = (known after apply)

                          + items {
                              + key  = (known after apply)
                              + mode = (known after apply)
                              + path = (known after apply)
                            }
                        }

                      + vsphere_volume {
                          + fs_type     = (known after apply)
                          + volume_path = (known after apply)
                        }
                    }
                }
            }
        }
    }

  # module.jetstream_debezium_ui.kubernetes_secret.auth_data_secret will be created
  + resource "kubernetes_secret" "auth_data_secret" {
      + data = (sensitive value)
      + id   = (known after apply)
      + type = "Opaque"

      + metadata {
          + annotations      = {
              + "checksum" = "52525e40a4d9ab51151433dc503d55a72bdc4be0a2a4f5b09f226c6e1f48f9eb"
            }
          + generation       = (known after apply)
          + labels           = {
              + "application" = "jetstream-debezium-ui"
              + "cluster"     = "bikeshed-red"
              + "environment" = "qa"
              + "region"      = "us-east-1"
              + "team"        = "data-platform"
            }
          + name             = "auth-data-secrets"
          + namespace        = "qa"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }

  # module.jetstream_debezium_ui.kubernetes_service.jetstream_debezium_ui_svc will be created
  + resource "kubernetes_service" "jetstream_debezium_ui_svc" {
      + id                    = (known after apply)
      + load_balancer_ingress = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + labels           = {
              + "application" = "jetstream-debezium-ui"
              + "cluster"     = "bikeshed-red"
              + "environment" = "qa"
              + "region"      = "us-east-1"
              + "team"        = "data-platform"
            }
          + name             = "jetstream-debezium-ui"
          + namespace        = "qa"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }

      + spec {
          + cluster_ip                  = (known after apply)
          + external_traffic_policy     = (known after apply)
          + health_check_node_port      = (known after apply)
          + publish_not_ready_addresses = false
          + selector                    = {
              + "application" = "jetstream-debezium-ui"
              + "component"   = "jetstream-debezium-ui"
            }
          + session_affinity            = "None"
          + type                        = "ClusterIP"

          + port {
              + name        = "http"
              + node_port   = (known after apply)
              + port        = 80
              + protocol    = "TCP"
              + target_port = "dbzui-port"
            }
        }
    }

  # module.jetstream_debezium_ui.module.cert.aws_acm_certificate.cert will be created
  + resource "aws_acm_certificate" "cert" {
      + arn                       = (known after apply)
      + domain_name               = "jetstream-debezium-ui.qa.us-east-1.mq01-qa.aws.marqeta.io"
      + domain_validation_options = [
          + {
              + domain_name           = "jetstream-debezium-ui.qa.us-east-1.mq01-qa.aws.marqeta.io"
              + resource_record_name  = (known after apply)
              + resource_record_type  = (known after apply)
              + resource_record_value = (known after apply)
            },
        ]
      + id                        = (known after apply)
      + status                    = (known after apply)
      + subject_alternative_names = (known after apply)
      + tags_all                  = (known after apply)
      + validation_emails         = (known after apply)
      + validation_method         = "DNS"
    }

  # module.jetstream_debezium_ui.module.cert.aws_acm_certificate_validation.cert will be created
  + resource "aws_acm_certificate_validation" "cert" {
      + certificate_arn         = (known after apply)
      + id                      = (known after apply)
      + validation_record_fqdns = (known after apply)
    }

  # module.jetstream_debezium_ui.module.cert.aws_route53_record.cert_validation[0] will be created
  + resource "aws_route53_record" "cert_validation" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = (known after apply)
      + records         = (known after apply)
      + ttl             = 60
      + type            = (known after apply)
      + zone_id         = "Z00728331PNYVN1WW537D"
    }

  # module.jetstream_debezium_ui.module.dns_record.aws_route53_record.hostnames["jetstream-debezium-ui.qa.us-east-1.mq01-qa.aws.marqeta.io"] will be created
  + resource "aws_route53_record" "hostnames" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "jetstream-debezium-ui.qa.us-east-1.mq01-qa.aws.marqeta.io"
      + records         = (known after apply)
      + ttl             = 60
      + type            = "CNAME"
      + zone_id         = "Z00728331PNYVN1WW537D"
    }

  # module.jetstream_debezium_ui.module.ingress.module.ingress_alb.kubernetes_ingress.this will be created
  + resource "kubernetes_ingress" "this" {
      + id                     = (known after apply)
      + load_balancer_ingress  = (known after apply)
      + wait_for_load_balancer = true

      + metadata {
          + annotations      = (known after apply)
          + generation       = (known after apply)
          + name             = "jetstream-debezium-ui-alb2-http"
          + namespace        = "qa"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }

      + spec {

          + rule {
              + host = "jetstream-debezium-ui.qa.us-east-1.mq01-qa.aws.marqeta.io"

              + http {
                  + path {
                      + path = "/*"

                      + backend {
                          + service_name = "jetstream-debezium-ui"
                          + service_port = "http"
                        }
                    }
                }
            }
        }
    }

Plan: 8 to add, 0 to change, 0 to destroy.

```

**Comment by rk3rn3r** [comment]
Hello @abhishekkh, first of all thank you for the contribution. Is there a Jira issue for this PR in the [Red Hat issue tracker](https://issues.redhat.com)?
If so, could you please prefix your commit messages and the PR title with the task id (like DBZ-1234)?
What is that QA plan comment above? Is this relevant for the PR?

What is the reason for removing the "Create Connector" button? Is this on purpose? Is that valid @indraraj?

**Comment by abhishekkh** [comment]
@rk3rn3r @indraraj Haven't raised a ticket yet, I have forked and pushed this image to our private ECR. 

The **create** button was removed as we didn't want users to create new connectors in prod without performing capacity analysis for the pods we already have in the cluster. It would be nice if we can have some ACLs that can control the operations that can be performed based on role assigned using okta etc. I also plan to remove the **delete** button.

Since I have your attention, is there a way to hide the _sasl.jaas.config_ in the connector details, similar to the database password? Asked this question on zulip chat as well. 

- typed from my phone

**Comment by rk3rn3r** [comment]
Hey @abhishekkh! Do you really want to make a PR or did you only require a branch for your local env? I am closing this one as 1) there's no config option for switching to basic auth, even this feels like an interesting addition. We might add this to the Debezium UI later in a separate PR. @indraraj could you maybe file a task for that?
2) we won't remove the create button.
I am closing this PR now. Feel free to open a new PR with dedicated changes when you want them merged into the main repo.

**Comment by abhishekkh** [comment]
Sure that works

**Comment by rk3rn3r** [comment]
@abhishekkh I just filed [DBZ-5459 ](https://issues.redhat.com/browse/DBZ-5459) to add some config options for customizing the Debezium UI. One subtask is the removal of the "Create Connector" button.

**Pull request closed without merging**
