### PR TITLE
DBZ-4066 Change Debezium UI configurations property names and update to latest UI config changes

### PR DESCRIPTION
**Pull request by rk3rn3r**
closes https://issues.redhat.com/browse/DBZ-4066

### CODE REVIEW

**Comment by rk3rn3r** [comment]
@gunnarmorling here's the PR to change the config properties of the Debezium UI (remove unnecessary `ui.base.uri`, rename `kafka.connect.uri` --> `kafka.connect.uris`, `validation.disabled` -->  `validation_disabled`)

**Comment by rk3rn3r** [comment]
@gunnarmorling the backend test run has that recurring problem that sometimes the build isn't properly started or the status report is wrong. Tests pass locally and I tested the UI frontend manually too.

@uidoyen @indraraj  can you have a look at the Cypress e2e tests? For me in Firefox the UI loads successfully and everything looks fine.

**Comment by uidoyen** [comment]
Tested locally. Cypress e2e tests looks good.

**Comment by uidoyen** [comment]
@gunnarmorling @rk3rn3r I tried after removing old images and able to reproduce it. I am getting the following API error

```
{"message":"Could not connect to Kafka Connect! Kafka Connect REST API is not available at \"http://localhost:8083\": RESTEASY004655: Unable to invoke request: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8083 [localhost/127.0.0.1] failed: Connection refused (Connection refused)","trace":"[io.debezium.configserver.rest.ConnectorResource.listConnectors(ConnectorResource.java:362), jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source), java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43), java.base/java.lang.reflect.Method.invoke(Method.java:566), org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170), org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130), org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643), org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507), org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457), org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364), org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459), org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419), org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393), org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68), org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492), org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261), org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161), org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364), org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164), org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247), io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73), io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138), io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41), io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93), org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415), org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452), org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29), org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29), java.base/java.lang.Thread.run(Thread.java:829), org.jboss.threads.JBossThread.run(JBossThread.java:501)]"}
```

running containers 
`docker ps -a`

```
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS                      PORTS                                                                     NAMES
833992b00725   debezium-ui_dbzui-backend       "/deployments/run-ja…"   19 minutes ago   Up 19 minutes               0.0.0.0:8080->8080/tcp, :::8080->8080/tcp                                 dbzui-backend
60971382bcaa   debezium-ui_dbzui-connect       "/docker-entrypoint.…"   19 minutes ago   Up 19 minutes               8778/tcp, 9092/tcp, 0.0.0.0:8083->8083/tcp, :::8083->8083/tcp, 9779/tcp   dbzui-connect
13dfb8e55a23   mongo:3.6                       "docker-entrypoint.s…"   19 minutes ago   Exited (0) 19 minutes ago                                                                             debezium-ui_mongo-initializer_1
09d50ef202c4   debezium/kafka:1.6              "/docker-entrypoint.…"   19 minutes ago   Up 19 minutes               8778/tcp, 9779/tcp, 0.0.0.0:9092->9092/tcp, :::9092->9092/tcp             dbzui-kafka
8f7d056ab6d3   debezium/zookeeper:1.6          "/docker-entrypoint.…"   19 minutes ago   Up 19 minutes               2181/tcp, 2888/tcp, 3888/tcp, 8778/tcp, 9779/tcp                          dbzui-zookeeper
e835d69d2f40   mongo:3.6                       "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes               0.0.0.0:37017->27017/tcp, :::37017->27017/tcp                             dbzui-db-mongo
b622a6ad7c7c   debezium/example-mysql:1.6      "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes               33060/tcp, 0.0.0.0:63306->3306/tcp, :::63306->3306/tcp                    dbzui-db-mysql
f112dbb42fd7   debezium/example-postgres:1.6   "docker-entrypoint.s…"   19 minutes ago   Up 19 minutes               0.0.0.0:65432->5432/tcp, :::65432->5432/tcp                               dbzui-db-pg
```

**Comment by rk3rn3r** [comment]
@gunnarmorling one issue was that I missed to rename the `kafka.connect.uri` parameter/env var for the e2e tests. The other was a problem with Debezium Connect 1.6 image in the connection to the Kafka container and the MySQL database. A new hostname for the Kafka container and using the `debezium` user for MySQL access solved the issue. Also I added some cleanup for Postgres tests as max_wal_senders broke these tests now with a 1.5/1.6 update.
Please review and merge!

**Comment by gunnarmorling** [comment]
Applied, thx!

**Pull request merged**
